### ISSUE TITLE
Example showcase

### ISSUE THREAD

**Issue by zernonia** [Dave136/vue-email#1]
Hi @Dave136 ! Awesome job porting React-email to Vue! It looks good!

I think adding a [Example](https://react.email/examples) page would really help devs to visually understand how to use it, and interested in using this package!

Cheers!

**Comment by Dave136** [comment]
Thanks for your suggestion, I'll work with some real examples using the library

**Comment by zernonia** [comment]
Absolutely beatiful @Dave136 !
