### ISSUE TITLE
Possible to render on server side

### ISSUE THREAD

**Issue by tylergets** [Dave136/vue-email#10]
Hey there, I am looking for a project just like this however from the documentation it appears like I can only render the vue templates within a browser, is this the case? 

Happy to contribute some examples if its not

Thanks!

**Comment by Flowko** [comment]
Hi, rn this is not possible as you require vue to compile/render the actuall template into html.

**Comment by tylergets** [comment]
Thanks; thats what I figured. I will look into this as well, the vue SSR documentation may be of help

https://vuejs.org/guide/scaling-up/ssr.html

**Comment by Flowko** [comment]
yes, i have checked it, and it works, but since we have custom components, im not sure how that plays with it

**Comment by mklueh** [comment]
Tried in Nuxt 3

```
import { defineEventHandler } from "h3";
import { createSSRApp } from "vue";
import { renderToString } from "vue/server-renderer";
import MyComponentfrom "~/components/MyComponent.vue";

export default defineEventHandler(async (event) => {
  return await renderToString(createSSRApp(MyComponent));
});

```

But it fails. 

Daniel Roe has written a few words about that issue and it does not look promising: https://github.com/nuxt/nuxt/issues/19854 

However, why shouldn't it work in plain Vue?

**Comment by Flowko** [comment]
What i meant with plain vue, is using only html elements, and rendering them using the vue ssr utilities, that works.
But no way to supply custom components and libraries to it.

**Comment by qin-guan** [comment]
A temporary workaround is to define the email component using `defineComponent` and importing that instead

**Comment by Flowko** [comment]
@qin-guan that was the plan using that along side the Create app works, but we trying to find an optimal solution that doesnt require the users to rewrite the emails twice, but thanks for sharing!

**Comment by v-moravec** [comment]
Hi, I believe this is possible, by adding this to `nuxt.config.ts`

```ts
import vuePlugin from '@vitejs/plugin-vue'

export default defineNuxtConfig({
  nitro: {
    rollupConfig: {
      // @ts-ignore
      plugins: [
        vuePlugin()
      ]
    },
  },
})
```
At least it's working for me.

**Comment by Dave136** [comment]
SSR support in the `0.6.0` release, please upgrade the library!
