### ISSUE TITLE
NUXT 3 | VERCEL | PRODUCTION BUILD : ReferenceError: __VUE_PROD_DEVTOOLS__ is not defined

### ISSUE THREAD

**Issue by ChronicStone** [Dave136/vue-email#102]
Hi, I can't seem to get the template compiler on production, on a Nuxt 3 app hosted on vercel (latest release of vue-email)

```
🚧 Compiling InvitationEmail file
💌 Generating output
🚧 Compiling InvitationEmail file
🌎 Injecting translations
🎉 Rendering template InvitationEmail
Unhandled Promise Rejection 	{"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"ReferenceError: __VUE_PROD_DEVTOOLS__ is not defined","reason":{"errorType":"ReferenceError","errorMessage":"__VUE_PROD_DEVTOOLS__ is not defined","stack":["ReferenceError: __VUE_PROD_DEVTOOLS__ is not defined","    at Object.install (file:///var/task/node_modules/@vue-email/compiler/dist/chunks/vue-i18n.mjs:5858:65)","    at Object.use (/var/task/node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:2892:18)","    at templateRender (file:///var/task/node_modules/@vue-email/compiler/dist/compiler.mjs:223:11)","    at async renderEmailTemplate (file:///var/task/chunks/_trpc_.mjs:2059:10)","    at async sendInvitationEmail (file:///var/task/chunks/_trpc_.mjs:2080:13)","    at async resolveMiddleware (file:///var/task/chunks/_trpc_.mjs:1013:30)","    at async callRecursive (file:///var/task/chunks/_trpc_.mjs:1049:32)","    at async callRecursive (file:///var/task/chunks/_trpc_.mjs:1049:32)","    at async callRecursive (file:///var/task/chunks/_trpc_.mjs:1049:32)","    at async resolve (file:///var/task/chunks/_trpc_.mjs:1079:24)"]},"promise":{},"stack":["Runtime.UnhandledPromiseRejection: ReferenceError: __VUE_PROD_DEVTOOLS__ is not defined","    at process.<anonymous> (file:///var/runtime/index.mjs:1276:17)","    at process.emit (node:events:529:35)","    at emit (node:internal/process/promises:149:20)","    at processPromiseRejections (node:internal/process/promises:283:27)","    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)"]}
Unknown application error occurred
Runtime.Unknown
```

Everything works fine locally, even if I build locally & run the build output, still no issues. Not too sure what other information might help you, but here's at least the nuxt info

------------------------------
- Operating System: Darwin
- Node Version:     v18.16.0
- Nuxt Version:     3.8.0
- CLI Version:      3.9.1
- Nitro Version:    2.7.2
- Package Manager:  pnpm@8.5.1
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

**Comment by linspw** [comment]
Same problem

**Comment by ChronicStone** [comment]
I've tried a lot of approaches to solve this, use vite to define __VUE_PROD_DEVTOOLS__, use the classic Node SDK, and a few other things, but nothing seem to let me go around this.

Also nuxt module devtool isn't working, but there's already an issue opened for this : #93

**Comment by linspw** [comment]
The issue arises when NODE_ENV is set to 'production' in my Express server environment. We need a solution similar to the following (though I'm unsure how to implement it in a simple TypeScript repository):

```ts
// https://github.com/intlify/vue-i18n-next/issues/789#issuecomment-1356782726
export default defineConfig({
  base: './',
  resolve: {
    alias: {
      // ...
      'vue-i18n': 'vue-i18n/dist/vue-i18n.runtime.esm-bundler.js',
    },
  },
})
```

https://github.com/intlify/vue-i18n-next/issues/789

**Comment by linspw** [comment]
Solution for rollup:

![image](https://github.com/Dave136/vue-email/assets/43552865/8bb476cd-30a9-4621-b671-1d3015321ab2)

**Comment by Dave136** [comment]
@linspw thanks a lot for this solution! I'll be working to fix that error.

**Comment by Dave136** [comment]
@ChronicStone the issue with the devtools is already fixed, soon I'll be launch the next beta release with a lot of fixed issues.

**Comment by linspw** [comment]
In typescript I made a fast fixing using:

```ts
global.__VUE_PROD_DEVTOOLS__ = false;
```

**Comment by Dave136** [comment]
@linspw the error is because i'm compiling including the `vue-i18n` dependency, to fix that i already added `vue-i18n` as external dependency.

In this way, if anyone want to use the i18n feature must be to install `vue-i18n`.

This would be fixed in the next beta release that i'm working on it

**Comment by linspw** [comment]
Great @Dave136 , this is perfect, thanks for your help and attention!
