### ISSUE TITLE
Error: Cannot find module 'vue/compiler-sfc'

### ISSUE THREAD

**Issue by desk-pro** [Dave136/vue-email#109]
Config : Nuxt 3.6.5, Node 18, Firebase 12.9.1

I have tried to use Vue Email and MailerSend Node.js SDK. When I deploy my project on firebase hosting, I have following error message : 

Function failed on loading user code. This is likely due to a bug in the user code. Error message: Provided module can't be loaded.
Did you list all required modules in the package.json dependencies?
Detailed stack trace: Error: Cannot find module 'vue/compiler-sfc'
Require stack:
- /workspace/node_modules/@vue-email/compiler/dist/compiler.cjs
- /workspace/index.js
- /layers/google.nodejs.functions-framework/functions-framework/node_modules/@google-cloud/functions-framework/build/src/loader.js
- /layers/google.nodejs.functions-framework/functions-framework/node_modules/@google-cloud/functions-framework/build/src/main.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/workspace/node_modules/@vue-email/compiler/dist/compiler.cjs:6:18)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    
So far, my functions/index.js looks like : 
```
const { MailerSend, EmailParams, Sender, Recipient } = require('mailersend');
const { config } = require('@vue-email/compiler');
...

const mailerSend = new MailerSend({
  apiKey: functions.config().mailersend.api_key,
});

const vueEmail = config("./templates");

async function sendEmail(emailData) {
  const { to, name, subject } = emailData;
  
  const sentFrom = new Sender("*****", "*****");
  const recipients = [new Recipient(to, name)];

  const template = await vueEmail.render("Welcome.vue", {
    props: {
      url: 'https://vuemail.net/',
    },
  });

  const emailParams = new EmailParams()
    .setFrom(sentFrom)
    .setTo(recipients)
    .setSubject(subject)
    .setHtml(template);

  try {
    await mailerSend.email.send(emailParams);
    return { message: "Email sent" };
  } catch (error) {
    console.error("Error sending email:", error);
    throw new functions.https.HttpsError('unknown', 'Failed to send email');
  }
};
```

My functions/templates/Welcome.vue looks like : 

```
<template>
  <e-html lang="en">
    <e-button :href="url">
      View on GitHub
    </e-button>
  </e-html>
</template>

<script setup>
const props = defineProps({
    url: String,
})
</script>
```

And my functions/package.json looks like : 

```
{
  "name": "functions",
  "description": "Cloud Functions for Firebase",
  "scripts": {
    "serve": "firebase emulators:start --only functions",
    "shell": "firebase functions:shell",
    "start": "npm run shell",
    "deploy": "firebase deploy --only functions",
    "logs": "firebase functions:log"
  },
  "engines": {
    "node": "18"
  },
  "main": "index.js",
  "dependencies": {
    "@vue-email/compiler": "^0.8.0-beta.4",
    "firebase-admin": "^11.11.0",
    "firebase-functions": "^4.5.0",
    "mailersend": "^2.2.0",
  },
  "devDependencies": {
    "firebase-functions-test": "^3.1.0"
  },
  "private": true
}
```

Am I missing something ?

**Comment by Dave136** [comment]
Hi! @desk-pro you need to install `vue` as dependency

**Comment by desk-pro** [comment]
Ow ! Thank you very much, you are right !

**Comment by desk-pro** [comment]
Config : Nuxt 3.6.5, Node 18, Firebase 12.9.1

I am using Vue Email and MailerSend Node.js SDK. I have written a firebase cloud function that uses vue-email. When I use it, the email is properly sent, but I get following error in the console : ReferenceError: __VUE_PROD_DEVTOOLS__ is not defined
and it stops the execution of the cloud function.
Do you know if there is a way to avoid this error ? Should I install Nuxt Devtools in my cloud functions ? It seems akward to install a visual tool in a backend environment.

The relevant part of my cloud function :
```
const mailerSend = new MailerSend({
  apiKey: functions.config().mailersend.api_key,
});
const vueEmail = config(
  "./templates", {
  options: {
    baseUrl: "**********",
  }
});

async function sendEmail(emailData) {
  const { typeOfEmail, to, name, subject, preview, formattedString, title, address, participants } = emailData;
  
  const sentFrom = new Sender("*********", "******");
  const recipients = [new Recipient(to, name)];

  const template = await vueEmail.render(typeOfEmail+".vue", {
    props: {
      url: '**********************',
      name: name,
      preview: preview,
      formattedString: formattedString, 
      title: title,
      location: address.street_number + " "+ address.route+ ", "+address.postal_code+ " "+address.locality,
      participants: participants
    },
  });

  const emailParams = new EmailParams()
    .setFrom(sentFrom)
    .setTo(recipients)
    .setSubject(subject)
    .setHtml(template);

  try {
    await mailerSend.email.send(emailParams);
    return { message: "Email sent" };
  } catch (error) {
    console.error("Error sending email:", error);
    throw new functions.https.HttpsError('unknown', 'Failed to send email');
  }
};
```

My packages.json : 

```
{
  "name": "functions",
  "description": "Cloud Functions for Firebase",
  "scripts": {
    "serve": "firebase emulators:start --only functions",
    "shell": "firebase functions:shell",
    "start": "npm run shell",
    "deploy": "firebase deploy --only functions",
    "logs": "firebase functions:log"
  },
  "engines": {
    "node": "18"
  },
  "main": "index.js",
  "dependencies": {
    "@vue-email/compiler": "^0.8.0-beta.4",
    "firebase-admin": "^11.11.0",
    "firebase-functions": "^4.5.0",
    "vue": "^3.3.8"
  },
  "devDependencies": {
    "firebase-functions-test": "^3.1.0"
  },
  "private": true
}
```

Thanks !
