### ISSUE TITLE
ReferenceError: __VUE_PROD_DEVTOOLS__ is not defined

### ISSUE THREAD

**Issue by desk-pro** [Dave136/vue-email#111]
Config : Nuxt 3.6.5, Node 18, Firebase 12.9.1

I am using Vue Email and MailerSend Node.js SDK. I wrote a firebase cloud function to send emails. The emails are properly sent but I get following error in the console : ReferenceError: __VUE_PROD_DEVTOOLS__ is not defined and it stops the execution of my function.

Do you know from where it comes from ? Should I install Nuxt Devtools in my firebase cloud functions environment ? It seems a bit akward since it is a visual tool.

Here is my package.json : 

```
{
  "name": "functions",
  "description": "Cloud Functions for Firebase",
  "scripts": {
    "serve": "firebase emulators:start --only functions",
    "shell": "firebase functions:shell",
    "start": "npm run shell",
    "deploy": "firebase deploy --only functions",
    "logs": "firebase functions:log"
  },
  "engines": {
    "node": "18"
  },
  "main": "index.js",
  "dependencies": {
    "@vue-email/compiler": "^0.8.0-beta.4",
    "firebase-admin": "^11.11.0",
    "firebase-functions": "^4.5.0",
    "vue": "^3.3.8"
  },
  "devDependencies": {
    "firebase-functions-test": "^3.1.0"
  },
  "private": true
}
```

**Comment by Dave136** [comment]
@desk-pro here you cand find some solutions for your problem:

https://github.com/Dave136/vue-email/issues/102

This error would be fixed in the next beta release!

**Comment by Dave136** [comment]
I'll close this issue cause already exists this issue
