### ISSUE TITLE
Page don't fully load in iOS

### ISSUE THREAD

**Issue by victj99** [Dave136/vue-email#112]
Hello

I have been reported a bug with the version of safari on iOS (<16).
I found this PR https://github.com/Dave136/vue-email/pull/85 and I also noticed that in version v0.8.0-beta.5 it comes out as fixed.

- fix(utils): blank page issue on iphone iOS due to lookbehind regex...

I have updated to version v0.8.0-beta.5 but the same problem shown in the image persists, I tried on the playground page and also comes out the error (I don't know if the playground is updated but I got the same message before updating).

![image](https://github.com/Dave136/vue-email/assets/44973221/3208e6fa-626f-4af4-acb2-4e5f66188ebd)

I don't think it's another dependency since I tried removing the vue-email beta 5 module (from my nuxt app) and the page loaded normally.

Regards

**Comment by pjhartin** [comment]
Experiencing the same issue on our Nuxt site. Breaks the entire JS of the app, making the site unusable. Reported by many customers but it was difficult to replicate without Browserstack. 

It appears the vue-email library is bundled with the client-side JS, despite only using it for server-side generated emails.

**Comment by Dave136** [comment]
@victj99 fixed on the `0.8.0-beta-6` release!
