### ISSUE TITLE
0.8.0-beta.5 is missing code changes in published package (regex fix)

### ISSUE THREAD

**Issue by pjhartin** [Dave136/vue-email#114]
We noticed today that a fix for a breaking issue is missing from the published NPM package in `0.8.0-beta.5`.
The code change that appears to be missing can be seen here and in the screenshots below: https://github.com/Dave136/vue-email/commit/f412221

We had hoped to use this release to fix issues that we are experiencing in production on iOS devices caused by this regex issue.
Please let us know if we can assist in republishing the changes.

## Source code
![CleanShot 2023-11-24 at 10 17 57@2x](https://github.com/Dave136/vue-email/assets/1385026/ed167693-0112-41af-af64-72c320fd27e8)

## Changes not published to NPM
![CleanShot 2023-11-24 at 10 22 19@2x](https://github.com/Dave136/vue-email/assets/1385026/8fff586d-49ae-4b21-9180-df20f211012d)

**Comment by Dave136** [comment]
@pjhartin thanks! You're right, i'll publish a new version to fix that!

**Comment by Dave136** [comment]
@pjhartin fixed on the `0.8.0-beta-6` release!
