### ISSUE TITLE
don't show props in html

### ISSUE THREAD

**Issue by veryPeriCloud** [Dave136/vue-email#115]
Hi! When I render html with useRender in this html props is undefined:
![image](https://github.com/Dave136/vue-email/assets/101694939/cacbe310-e0cd-4741-8947-28b15abdb0ee)

Result: 
![image](https://github.com/Dave136/vue-email/assets/101694939/875b5087-6ace-4719-b2ec-5f9a17f857e6)

What could be the problem?

**Comment by kenechukwuJosiah** [comment]
@veryPeriCloud, could you please share your template as well so that I can better understand what the problem is.

**Comment by veryPeriCloud** [comment]
In page:
![image](https://github.com/Dave136/vue-email/assets/101694939/e317298b-32bf-4cb3-8f09-fa8639d543d4)

In template:
![image](https://github.com/Dave136/vue-email/assets/101694939/f11d5f7e-a6db-40de-ac88-db0d1633be54)
![image](https://github.com/Dave136/vue-email/assets/101694939/aa94067b-08a3-4250-83f7-5f585ce5728c)

**Comment by Dave136** [comment]
Hi @veryPeriCloud, you need to pass the props as follows:

```ts
const html = await useRender(AuthAction, { props: { preview: "", href: "" }});
```
