### ISSUE TITLE
Devtools integration seems to be broken

### ISSUE THREAD

**Issue by genu** [Dave136/vue-email#119]
Hi, I just started playing around with `vue-email` but I noticed there is an issue in the nuxt integration:

From what I can tell, the client isn't actually included in the nuxt package. Should that be?

![CleanShot 2023-12-02 at 11 17 26](https://github.com/Dave136/vue-email/assets/928780/fb02836a-bd30-4ab6-9364-611653a92ffc)

**Comment by csprance** [comment]
Same problem here. If it helps I'm on an older version of nuxt 3.6

**Comment by gkTim** [comment]
We also have this problem with nuxt 3.8.2

**Comment by BayBreezy** [comment]
Thanks for the fix ❤️
