### ISSUE TITLE
Dependencies should be externalized for SSR

### ISSUE THREAD

**Issue by qin-guan** [Dave136/vue-email#19]
Currently, the dependencies such as `isomorphic-dompurify` are not externalized by Vite. 

This causes issues when using the lib in an SSR context as the bundled `isomorphic-dompurify` requires the `window` object.

## Proposed solution

Add `isomorphic-dompurify` and other deps to be externalized.

Would be happy to open a PR for this! (:

**Comment by Flowko** [comment]
you are welcome to open PRs, but for this speciifc reason,we'll include it with the release that will introduce the SSR support, as we still thinking on how to go about SSR for this library, thanks tho!
