### ISSUE TITLE
[feature][client app]: email preview with email grouping

### ISSUE THREAD

**Issue by cpreston321** [Dave136/vue-email#36]
I would love to organize my emails based on folders then it render the tree on the left side bar.

Folder `emails/` = "All Emails"

Folder `emails/Company/newsletter.vue` 

- All Emails 
  - Company
    - newsletter
  - [...reset_of_emails]

---
  
This could be useful as it helps organize it and doesn't contain everything in on subfolder within the view.

**Comment by Flowko** [comment]
hi, yeah good idea, we'll work on adding it ot he nuxt client, thanks
