### ISSUE TITLE
Deno Support

### ISSUE THREAD

**Issue by Niki2k1** [Dave136/vue-email#46]
I want to use this library to compile the vue templates in a Deno environment. The only thing that stops me from doing that ist the _isomorphic-dompurify_ library. The lib calls to the [node vm api](https://nodejs.org/api/vm.html) which is/will not be supported in Deno.
I did a little digging and found out you guys are just using the Library for Sanitizing, is there another Library you could use for that? Like [sanitize-html](https://www.npmjs.com/package/sanitize-html)

Or is there something that would speak against that?

I would like to contribute if we come to an agreement.

**Comment by Flowko** [comment]
hi there, we are in the process of updating our bundler, i saw u opened #47 i'll test those changes on the bundler branch and let u know

**Comment by Niki2k1** [comment]
@Flowko awesome thank you

**Comment by Flowko** [comment]
hi, before we continue can you share a reproduction using deno, as well test the latest version `0.6.2` which uses a different bundler, not sure if that might resolve the issue, but worth checking

**Comment by Niki2k1** [comment]
@Flowko Made a repo where you can test it, seems to be a different error/problem now
https://github.com/Niki2k1/deno-vue-email-test

**Comment by Flowko** [comment]
that issue seems to be coming from `module-from-string` we are looking at ways to make this library support deno as well, but it'll take some time, we'll update you here once we have something

**Comment by Dave136** [comment]
Hey @Niki2k1 , today we're introduce a new beta version, with support for deno, bun and nodejs!

You can see the docs [here](https://www.vuemail.net/server-side-rendering/deno)

**Comment by Niki2k1** [comment]
Awesome, tried it out today. Apart from umlauts not working everything seems to be working flawlessly. Thank you very much

**Comment by iPy849** [comment]
Is there any documentation about `vue-email/compiler`? I can't find anything in [the website](https://vuemail.net).
