### ISSUE TITLE
Deepmerge ESM in html-to-text dependancy

### ISSUE THREAD

**Issue by Saganic** [Dave136/vue-email#48]
Hi @Dave136, 

I can't seem to get the package to work in a Nuxt repo.

Looks like deepmerge isn't providing an es module for html-to-text:

```Uncaught SyntaxError: The requested module '/_nuxt/node_modules/.pnpm/deepmerge@4.3.1/node_modules/deepmerge/dist/cjs.js?v=74dcc2a2' does not provide an export named 'default' (at html-to-text.mjs?v=74dcc2a2:4:8)```

**Repro**
Clone this repo, copy vue-email/playgrounds/nuxt into its own project, remove the aliasing to vue-email and run the project.

**Comment by Flowko** [comment]
Hi, we are aware of this issue, and we are in the process of updating the bundler to resolve this type of issues, will let u know when we have it fixed, thanks

**Comment by Saganic** [comment]
@Flowko are there any suggestions to patch and get the project working in the meantime?

**Comment by Flowko** [comment]
it should be fixed in `0.6.2` if you can test and let us know

**Comment by v-moravec** [comment]
Hi, the error mentioned is gone, but it fails to do anything now. Here is new error that I'm getting:

```
[nuxt] [request error] [unhandled] [500] 'import' statement of ES modules is not supported                                               8:40:15 AM
Use asynchronous function 'importFromString' instead or replace it with dynamic 'import()' expression.
  at importFromStringSync (./node_modules/module-from-string/dist/index.mjs:247:13)  
  at templateRender (./.nuxt/dev/index.mjs:10173:21)  
  at useCompiler (./.nuxt/dev/index.mjs:10240:26)  
  at async ./.nuxt/dev/index.mjs:10255:16  
  at async Object.handler (./node_modules/h3/dist/index.mjs:1284:19)  
  at async Server.toNodeHandle (./node_modules/h3/dist/index.mjs:1359:7)
```

**Comment by Flowko** [comment]
Can remove ur node_modules folder and lock file, and install again?

**Comment by v-moravec** [comment]
I tried that didn't work, here is reproduction - https://github.com/v-moravec/nuxt-vue-email/
Just do `yarn install`, `yarn dev` and go to https://localhost:3000/api/email
