### ISSUE TITLE
Import error in Nuxt

### ISSUE THREAD

**Issue by v-moravec** [Dave136/vue-email#49]
Hi, I'm getting an error in VS Code when importing the compiler composable.

<img width="874" alt="image" src="https://github.com/Dave136/vue-email/assets/61109712/8d280e96-857d-4c8f-8c68-5b07aa9fff95">

Otherwise it works.

**Comment by Flowko** [comment]
we are aware of that issue, we are working on resolving it, thanks

**Comment by Flowko** [comment]
should be fixed in `0.6.2`, let us know if its not, thanks
