### ISSUE TITLE
importFromString ES modules issue

### ISSUE THREAD

**Issue by Flowko** [Dave136/vue-email#51]
```bash
[nuxt] [request error] [unhandled] [500] 'import' statement of ES modules is not supported
Use asynchronous function 'importFromString' instead or replace it with dynamic 'import()' expression.
  at Module.importFromStringSync (./node_modules/module-from-string/dist/index.mjs:267:13)  
  at templateRender (./.nuxt/dev/index.mjs:9437:102)  
  at useCompiler (./.nuxt/dev/index.mjs:9515:26)  
  at async eval (./.nuxt/dev/index.mjs:9530:16)  
  at async Object.eval (./node_modules/h3/dist/index.mjs:1386:19)  
  at async Server.toNodeHandle (./node_modules/h3/dist/index.mjs:1461:7)
  ```

reproduction:
https://github.com/v-moravec/nuxt-vue-email/
https://stackblitz.com/edit/github-9eaosg?file=emails%2FOptilynx.vue

found by:
@v-moravec

related:
#48

**Comment by Flowko** [comment]
@v-moravec can u try `0.6.4-4` and let me know please ?

**Comment by v-moravec** [comment]
Still the same issue 😞

**Comment by Flowko** [comment]
weird, cus it seems to be working here https://stackblitz.com/edit/github-9eaosg?file=emails%2FOptilynx.vue

**Comment by Flowko** [comment]
https://stackblitz.com/edit/github-9eaosg?file=emails%2FOptilynx.vue,package.json
ah i see, can u remove this 
![image](https://github.com/Dave136/vue-email/assets/35883748/0554c98b-e421-49cb-b0c9-7b97f6bcfde3)

we are already auto importing them, so u dont have to add them again

**Comment by Flowko** [comment]
nice, glad its working, let us know if u find anything else, ill close this and update the docs
