### ISSUE TITLE
Fresh Nuxt 3 install on Vercel: The package "esbuild-linux-64" could not be found

### ISSUE THREAD

**Issue by birdlavv** [Dave136/vue-email#58]
Reproduction:

> Repo: https://github.com/birdlavv/vue-email-reproduction
> Vercel deploy: https://vue-email-repro.vercel.app/api/test

The reproduction was made by

1. Creating a blank Nuxt 3 project
2. Installing `vue-email`
3. Adding `WelcomeEmail.vue`
4. Adding `/api/test.ts`

```import { useCompiler } from '#vue-email'
export default defineEventHandler(async (event) => {
  const template = await useCompiler('WelcomeEmail.vue')
  return template
})
```

Any assistance/insight into what is causing this would be greatly appreciated.

Possible related issues:

> https://github.com/vercel/vercel/issues/7287
> https://github.com/evanw/esbuild/issues/1819

**Comment by birdlavv** [comment]
Yes @Dave136 , it works as expected in development but breaks at deployment runtime. There don't seem to be any build warnings or errors. I do not yet know if this is a cross-platform error or if it is specific to Vercel.

**Comment by Dave136** [comment]
@birdlavv I test the nuxt implementation, `npm` and `yarn` throw error, it seems it's a issue with esbuild.

I suggest you use `pnpm`, it resolves as well.

I created a repo, where i tested the functionalities, open the terminal, click the button and you can see the result.

Here i left you the repo and production link:

- Repo [github](https://github.com/Dave136/nuxt-vue-email-example)
- Prod [working example](https://nuxt-vue-email-example-ir19r7zvw-davejs136.vercel.app/)

**Comment by birdlaw-cheetahbooking** [comment]
I can confirm that using `pnpm` as a workaround works on Vercel.
Thanks, @Dave136!

**Comment by chang-ryan** [comment]
Hi guys, how do you get Vercel to use `pnpm`?
