### ISSUE TITLE
Is there a way too create a base component?

### ISSUE THREAD

**Issue by bitfactory-michel-lubbers** [Dave136/vue-email#64]
I have installed this package as is in a project.
And i saw too create a email you need to write the css and layout in every template.

I was not able to find how to import a custom component inside the email template.
When i tried i got the following error
```
[Vue warn]: Failed to resolve component: EmailLayout
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
```

Filestructuur:
- components
-- EmailLayout.vue failed in loading
- emails
-- EmailTemplate.vue
-- EmailLayout.vue failed in loading

email - layout
```
<template>
    <EHtml :lang="lang">
        <slot />
    </EHtml>
</template>

<script lang="ts" setup>
import { defineComponent } from 'vue';
import { EHtml } from 'vue-email';

export default defineComponent({
    name: 'EmailLayout',
    props: {
        lang: {
            type: String,
            default: 'en',
        },
    },
})
</script>
```
email - template
```
<template>
    <EmailLayout>
        <e-button :href="url">View on GitHub</e-button>
    </EmailLayout>
</template>

<script lang="ts" setup>
defineProps<{ url: string }>();
</script>
```

**Comment by Flowko** [comment]
do u have a reproduction for this ? would help us see whats going on better

**Comment by bitfactory-michel-lubbers** [comment]
I have zipped what i currently have. Because i haven't put it live yet.
It is a simple test project.
I just do `npm run dev` and go too the api url to test it `http://localhost:3000/api/email/register`
In my terminal it returns the the errors mention above.

[testingVueEmail.zip](https://github.com/Dave136/vue-email/files/12505961/testingVueEmail.zip)

**Comment by Flowko** [comment]
okay will give it a try, thanks

**Comment by Flowko** [comment]
yeah, so this is a bug, as we dont handle outside components on ssr, cus the context is not the same as the nuxt context, we handle the vue component conversion outside of nuxt, which is why it doesnt work, we'll try to see if we can fix this for good, but for now i advice to copy paste the same components code in each template, till we find a solution

**Comment by bitfactory-michel-lubbers** [comment]
@Flowko Oke thank you for the quick response.
I will just use it as you suggested.

**Comment by nandi95** [comment]
It would be nice if other imports would be allowed too. I already have a tailwind config in the project and if possible I don't want to duplicate it.

**Comment by Flowko** [comment]
i honestly cant think of ways to make that possible, the thing is, once you build your app, its a whole another story, we cant have access to anything on the vue runtime in the server, as far as i know, im afraid i cant make that possible, there might be a way, but that migth depend on having another api and the files will have to live outside of the nuxt project, either way, its hard to achive that with what vue/nuxt provides

**Comment by nandi95** [comment]
Is it not possible to use vue ssr to render? Anything that would aid this in nuxt?
A way around it maybe, that a config can be introduced that sets the base component that the email will be wrapped in?

**Comment by Flowko** [comment]
we will keep trying to find solutions, till then, will keep you posted

**Comment by nandi95** [comment]
can seem to import types either
```ts
import type { FormInput } from '~/types';
import type { PropType } from 'vue';

// typehint what is passed in as props
defineProps<{ [K in keyof FormInput]: PropType<FormInput[K]> }>();
```

**Comment by L422Y** [comment]
We already use templates and vue-email components, can't we add a separate folder for custom email components and load those like the built-in vue-email ones?

**Comment by Flowko** [comment]
we added a checklist to here, so u guys know whats supported and whats not:
https://www.vuemail.net/getting-started/ssr#features

i cant figure out a way to handle that on the server plus with the tiny amount of time i have to work on this library, we only managed to make a tiny compiler that can get the normal/simple vue file to render with no import support but only able to handle the `vue-email` compoennts, but then you have `nuxt` to think about, cus it handles server side logic differently.

contributions are more than welcome, but till we figure out how to do that, you guys will have to stick with what the library has to offer.

**Comment by L422Y** [comment]
Ah I see you are importing the other components statically...  would this not work for some reason? 
I tried playing with it but I don't have my head wrapped around the project as well as maybe someone else does.

```
export function loadComponents(app: App<Element>) {
  const components = import.meta.glob('../../**/email-components/**/*.vue')
  for (const filePath in components) {
    if (!filePath) continue
    const name = filePath?.split('/').pop()?.replace('.vue', '')
    if (!name) continue
    app.component(
      name,
      defineComponent(() => components[filePath]),
    )
  }
}
```

I do dynamic imports like this for a modular monitoring application I am working on and they work.

**Comment by Flowko** [comment]
I'll check it out and get back to you

**Comment by Flowko** [comment]
@L422Y could you pelase test `0.7.1-pre.2` you can now be able to import your components, for naming you use the same vue naming conventions `pascalCase` ex: `Layout/Default.vue` -> `LayoutDefault`

**Comment by Flowko** [comment]
@L422Y @bitfactory-michel-lubbers if you could pelase test `0.7.1-pre.4` the components that live inside the `emails` folder will be auto imported, for naming you use the same vue naming conventions `pascalCase` ex: `Layout/Default.vue` -> `LayoutDefault`  
no need to import those components in ur email template, just add them to your code `<LayoutDefault>...</LayoutDefault>`

let me know if u get any errors

**Comment by L422Y** [comment]
Will try later this evening!

**Comment by L422Y** [comment]
If I change the path in the import i.e.`import EmailLayout from "../../emails/EmailLayout.vue"` it tries to load the file, but it cannot parse:

```bash
Error loading component /Users/larry/Development/apps/redacted/emails/EmailLayout.vue:1
<template>
^

SyntaxError: Unexpected token '<'
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1153:20)
    at Module._compile (node:internal/modules/cjs/loader:1205:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at /Users/larry/Development/apps/redacted/.nuxt/dev/[object Promise].js:45:34
    at Script.runInContext (node:vm:133:12)
[nitro] [unhandledRejection] Error: Component NewBid not found
    at templateRender (/Users/larry/Development/apps/redacted/node_modules/vue-email/dist/compiler.mjs:305:11)
    at useCompiler (/Users/larry/Development/apps/redacted/node_modules/vue-email/dist/runtime/server/services/useCompiler.mjs:18:26)
    at sendEmail (/Users/larry/Development/apps/redacted/server/utils/send-email.ts:18:18)

```

**Comment by L422Y** [comment]
We can add the emails folder to our nuxt.config.ts and then the IDE doesn't complain anymore, and everything works:

```
export default defineNuxtConfig({
  components: [
        '~/components',
        '~/emails',
    ],
})
```

**Comment by Flowko** [comment]
thanks alot for taking the time to test this, i'll add it to the compoennts folder in the nuxt module, so you dont have to,
can you test `0.7.1-pre.7`, also just remove `'~/emails',` from your nuxt config

**Comment by L422Y** [comment]
Updated to `0.7.1-pre.7` and when I remove that from my config, the IDE complains again:

<img width="496" alt="image" src="https://github.com/Dave136/vue-email/assets/156414/4602c8b4-52c9-41e1-ab71-623623b7a8cf">

**Comment by Flowko** [comment]
hmm, can u maybe do a quick restart to your IDE ?

**Comment by Flowko** [comment]
ah my bad, i addded a prefix to those compoennts, so it shouild be `EmailsEmailLayout` let me fix it

**Comment by L422Y** [comment]
Yep that's it :) 
<img width="601" alt="image" src="https://github.com/Dave136/vue-email/assets/156414/63a51c44-c4be-4248-88b4-153c54c98b05">

**Comment by Flowko** [comment]
also if u can build and test it that would be great

**Comment by L422Y** [comment]
`0.7.1-pre.8` works great for me, did have to coax webstorm to reload the generated types in .nuxt/components.d.ts but after that I've got no problems

**Comment by Flowko** [comment]
yeah, that issue im facing with vscode as well, but good that its working, thanks alot, will wrap it later today and make a new release, will update here once its done

**Comment by Flowko** [comment]
Release under version `0.7.1`

**Comment by stijns96** [comment]
> It would be nice if other imports would be allowed too. I already have a tailwind config in the project, and if possible I don't want to duplicate it. (currently I'm importing it in the script and passing it as a prop)
> 
> Or perhaps use a composable and in nuxt the useRuntimeConfig()

I really like to see this feature as well. It doesn't feel good to duplicate the config or to pass it as a prop...

**Comment by Flowko** [comment]
@stijns96 yeah im working on adding that #72

**Comment by Flowko** [comment]
@stijns96 available in the latest version of vue email packages
