### ISSUE TITLE
BunJS support

### ISSUE THREAD

**Issue by IgnisDa** [Dave136/vue-email#70]
It would be great if vue-email supports [Bun](https://bun.sh).

Here is the error currently:

![image](https://github.com/Dave136/vue-email/assets/60938164/1fa5bfa1-7d03-4eb1-b4b3-a24c7eeac263)

**Comment by Dave136** [comment]
Sure! We'll add support to `Bun` when fix some internal issues

**Comment by Flowko** [comment]
@IgnisDa can u please check `0.7.1-pre.4` and let us know if it works for you, also if u get errors or anythign, please do share the code that u are using, so we can check it out

**Comment by IgnisDa** [comment]
@Flowko I tried with the version you mentioned and the code is same as the screenshot I have above. I get this error:

![image](https://github.com/Dave136/vue-email/assets/60938164/2d620471-2ba5-4193-9c0d-65edeffb4b3e)

**Comment by Flowko** [comment]
By the code i meant the template code, like App.vue, if u can share that, that would help

**Comment by IgnisDa** [comment]
Nothing special:

```vue
<script setup>
// Import what you need from vue.
import { defineProps, computed } from 'vue'

defineProps({
  name: String
})

const username = computed(() => name.value.toUpperCase())
</script>

<template>
  <section>
    <h1>Welcome {{ username }}</h1>
  </section>
</template>
```

**Comment by Flowko** [comment]
oh damn, your code is wrong:
it should be like this:
```vue
<script setup>
// Import what you need from vue.
import { defineProps, computed } from "vue";

const props = defineProps({
  name: String,
});

const username = computed(() => props.name.toUpperCase());
</script>

<template>
  <section>
    <h1>Welcome {{ username }}</h1>
  </section>
</template>
```

**Comment by Flowko** [comment]
lol i just saw we have the same code in the docs, will fix that as well

**Comment by IgnisDa** [comment]
Yeah I took it from the docs.

**Comment by IgnisDa** [comment]
@Flowko I created a file with the vue code you pasted above. Here is the error:

![image](https://github.com/Dave136/vue-email/assets/60938164/92da01bf-eb6f-4978-9a33-05da87d4ab37)

**Comment by IgnisDa** [comment]
![image](https://github.com/Dave136/vue-email/assets/60938164/ad47989d-5cb9-47d1-9e1b-371f595fa11e)

(in case required)

**Comment by IgnisDa** [comment]
Wait I got it working.

**Comment by Flowko** [comment]
really? what changed ?

**Comment by IgnisDa** [comment]
I had a syntax error in my component, thats why it was not working. I fixed it, now it renders fine. It does have other warning though.

**Comment by IgnisDa** [comment]
![image](https://github.com/Dave136/vue-email/assets/60938164/3bcbe4f2-bae4-41d9-8897-68d0a1d9fc94)

**Comment by IgnisDa** [comment]
```vue
<script setup lang="ts">
import { defineProps, computed } from "vue";

const props = defineProps({
  name: String,
});

const username = computed(() => props.name.toUpperCase());
</script>

<template>
  <section>
    <h1>Welcome {{ username }}</h1>
  </section>
</template>
```

**Comment by Flowko** [comment]
can u go back to the previous version `0.7.1-pre.4` and check

**Comment by IgnisDa** [comment]
It does render but I get the same `Error loading component`

**Comment by Flowko** [comment]
okay, best i check this on my machine, will update you here

**Comment by Flowko** [comment]
would you be able to put that code in a github repo ? just so i have the same code as you

**Comment by IgnisDa** [comment]
https://github.com/IgnisDa/mails

**Comment by Flowko** [comment]
fixed, it was because you have other files in the `src` folder other than `.vue` its best to move your email files to a differnet folder, so you dont get issues later on, try `0.7.1-pre.6` i just tested it against your code and it seems to be working fine:

![image](https://github.com/Dave136/vue-email/assets/35883748/f46ab0c4-584d-4937-adab-a70b293b5622)

test and let me know please

**Comment by IgnisDa** [comment]
Yep it works now with `bun run index.ts`. However it does not work with `bun build`:
![image](https://github.com/Dave136/vue-email/assets/60938164/691123a2-db40-4ff6-9296-136053d7f992)

**Comment by Flowko** [comment]
ok, will check

**Comment by Flowko** [comment]
honestly no idea, im not yet famailar with how bun works, @Dave136 if you can take a look at this, check with `0.7.1-pre.6` and this repo https://github.com/IgnisDa/mails

**Comment by Dave136** [comment]
@Flowko i'll check this out

**Comment by Dave136** [comment]
@IgnisDa Bun is trying to compile including the vue source code, for this it has a flag to solve it, you can do the following:

```console
bun build --compile index.ts --target=bun --outfile index --external vue
```
> **target** could be `bun`, `node` or `browser`

Compiling not works, cause, you'll need vue as dependency unless you find a way to pass the vue path to the compiled file.

**Comment by Dave136** [comment]
@IgnisDa is just a madness example, but, for the compiled works, you'll need to pass the `vue` package

**Comment by Dave136** [comment]
@IgnisDa please upgrade to lastest version of the package `0.7.1`
