### ISSUE TITLE
'vue-email/compiler' import not working in typescript "Common.js" mode

### ISSUE THREAD

**Issue by vikingmute** [Dave136/vue-email#88]
Hey,

When attempting to import the 'vue-email/compiler' into my SSR-enabled backend project, I encountered an error. It seems that the library may not be fully compatible with the older project's setup (typescript in common.js mode). The specific error message I received is 
"Cannot find module 'vue-email/compiler' or its corresponding type declarations.ts(2307)"

Some of my tsconfig.json :

```
    "target": "es2017",
    "module": "CommonJS",
    "strict": true,
    "noImplicitAny": false,
    "experimentalDecorators": true,
    "esModuleInterop": true,
    "emitDecoratorMetadata": true,
```
Is there an alternate way I can import the compiler in CommonJS module?

**Comment by Dave136** [comment]
Can you show me how are you doing on the entry file? your `index` o where are u doing for compile template?

**Comment by vikingmute** [comment]
Sure ! @Dave136 
these are my screenshots for entry file and tsconfig.json file.
<img width="840" alt="屏幕快照 2023-10-14 上午11 24 49" src="https://github.com/Dave136/vue-email/assets/343954/3dd2cd53-0530-48bd-ba44-fb8aa97bf1a2">


<img width="533" alt="屏幕快照 2023-10-14 上午11 24 59" src="https://github.com/Dave136/vue-email/assets/343954/aa9d1e23-93e5-4300-87c0-0048d9504f10">

**Comment by madebyfabian** [comment]
I can confirm, though I am in an esm project:

```json
{
	"$schema": "https://json.schemastore.org/tsconfig",
	"display": "Default",
	"compilerOptions": {
		"module": "ESNext",
		"target": "ESNext",
		"composite": false,
		"declaration": true,
		"declarationMap": true,
		"esModuleInterop": true,
		"forceConsistentCasingInFileNames": true,
		"inlineSources": false,
		"isolatedModules": true,
		"moduleResolution": "node",
		"noUnusedLocals": false,
		"noUnusedParameters": false,
		"preserveWatchOutput": true,
		"skipLibCheck": true,
		"strict": true
	},
	"exclude": ["node_modules"]
}
```

**Comment by Dave136** [comment]
@vikingmute  @madebyfabian thanks! I'll check this out

**Comment by madebyfabian** [comment]
Hi @Dave136 stumbling over this again, where you able to check what the reason is or maybe a hotfix?
