### ISSUE TITLE
Cannot install v0.8.0-beta3

### ISSUE THREAD

**Issue by iBobik** [Dave136/vue-email#91]
Hi, just tried to install it, but Nuxt cannot find the module:
```
Error while requiring module vue-email/nuxt: Error: Cannot find module 'myproject/vue-email/nuxt'
```

When downgraded to 0.7.2 it works now.

**Comment by Dave136** [comment]
@iBobik now you need to install it:

```sh
pnpm add @vue-email/nuxt
```

**Comment by iBobik** [comment]
Thank you for a quick reply :-)

Aha, that was not mentioned in the docs: https://www.vuemail.net/getting-started/installation

Now Nuxt does not complain, but Devtools panes disappeared (it was there with 0.7.2).

**Comment by Dave136** [comment]
@iBobik yes, the current beta version has some things to fix.

Thanks for your feedback!
