### ISSUE TITLE
Devtools cannot load

### ISSUE THREAD

**Issue by iBobik** [Dave136/vue-email#93]
After install and minimal e-mail template created I tried to see it in the Devtools, but the panel opens 404 (in my project) or welcome page in Nuxt quickstart template.

![Snímek obrazovky 2023-10-17 v 1 29 00](https://github.com/Dave136/vue-email/assets/614232/34ff2dfe-59a6-4f87-b060-e0fe039c5669)

Repro: https://stackblitz.com/edit/github-hdqsmc

**Comment by Dave136** [comment]
@iBobik i'll fix this on the next beta release

Thanks for the feedback!

**Comment by csprance** [comment]
Same here I get a 
![image](https://github.com/Dave136/vue-email/assets/7902617/82ab8e96-9259-4bcd-8208-457bdb520c5d)

**Comment by BayBreezy** [comment]
Leaving a comment here so I get notified when this is fixed. Thanks

**Comment by csprance** [comment]
Any ideas on how to fix this? Would love to make a pr for this but I'm not sure where to start.

**Comment by nikolasdas** [comment]
@Dave136 I still get the same error as @csprance has posted, using 0.8.0-beta.5 :/

**Comment by csprance** [comment]
Ditto. I get the same. If it helps I'm not on the latest nuxt. 

I'm on 3.6.1 I know there were a few vite changes maybe that's an issue?
